version: '3.4'

services:
  redis:
    container_name: redis
    image: redislabs/redis:latest
    cap_add:
      - SYS_RESOURCE
    ports:
      - 8443:8443/tcp
      - 9443:9443/tcp
      - 12000-12050:12000-12050/tcp

  grafana:
    container_name: grafana
    image: ghcr.io/redisgrafana/redis-explorer:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      # - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=redis-explorer-app
    volumes:
      - ./provisioning/plugins:/etc/grafana/provisioning/plugins
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
