version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/redisgrafana/redis-app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=redis-explorer-app
      # Uncomment to run in debug mode
      # - GF_LOG_LEVEL=debug
    volumes:
      - ../dist:/var/lib/grafana/plugins/redis-explorer-app
      - ../provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
